### PR TITLE
Remove kevinmkane per kevinmkane

### PR DESCRIPTION
**Pull request by ryjones**

### CODE REVIEW

**Review by thb-sb — APPROVED** [review]

**Comment by ryjones** [comment]
@kevinmkane is this correct?

**Comment by kevinmkane** [comment]
> @kevinmkane is this correct?

Yes. I'm no longer active on this project.

**Comment by ryjones** [comment]
> > @kevinmkane is this correct?
> 
> Yes. I'm no longer active on this project.

thank you!

**Comment by Naomi-Wash** [comment]
Kevin has noted that their involvement with OQS has ended, and is no longer an active maintainer on the project.

**Pull request merged**
