### PR TITLE
Add 2024-11-19 minutes

### PR DESCRIPTION
**Pull request by SWilson4**

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
@jplomas I saw you tried to join the call via an old Zoom link. We've moved the weekly OQS status calls over to the Linux Foundation's Zoom platform. The Zoom links can be found on the [PQCA calendar](https://pqca.org/calendar/) or in the agendas that I post in this repository or in the emails to the [OQS TSC mailing list](https://lists.pqca.org/g/main/subgroups).

**Comment by jplomas** [comment]
Thanks @dstebila I joined what I thought was 5 mins late due to an overlap and LF Zoom was empty. Tried the old Waterloo link to make sure the meeting hadn't been moved back there. Can't understand what went wrong but I'm putting it down to one of those weeks... 🤷

**Comment by dstebila** [comment]
> Thanks @dstebila I joined what I thought was 5 mins late due to an overlap and LF Zoom was empty. Tried the old Waterloo link to make sure the meeting hadn't been moved back there. Can't understand what went wrong but I'm putting it down to one of those weeks... 🤷

The LF Zoom room alternates every other week because it was not possible to set up a single recurring meeting with two different times on alternating weeks. So there are technically two LF OQS status meeting Zoom rooms depending on which week it is.

**Comment by jplomas** [comment]
> The LF Zoom room alternates every other week because it was not possible to set up a single recurring meeting with two different times on alternating weeks. So there are technically two LF OQS status meeting Zoom rooms depending on which week it is.

I thought I had joined via the https://zoom-lfx.platform.linuxfoundation.org/ link which has always accounted for that. Either way, my apologies 🙏

**Pull request merged**
